# apiVersion: v1
# kind: Service
# metadata:
#   name: pi-app-server
# spec:
#   selector:
#     app: pi-app-server
#   ports:
#   - port: 80
#     targetPort: 80
#   type: LoadBalancer  
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: pi-app-auth
# spec:
#   selector:
#     app: pi-app-auth
#   ports:
#   - port: 8081
#     targetPort: 8081
#   type: ClusterIP
# ---
apiVersion: v1
kind: Service
metadata:
  name: pi-app-user
spec:
  selector:
    app: pi-app-user
  ports:
  - port: 8081
    targetPort: 8081
  type: ClusterIP