service:
  mode: debug
  port: :8081

database:
  type: postgres
  port: 5432
  user: ${GOOGLE_CLOUD_POSTGRESQL_DB_USER}
  password: ${GOOGLE_CLOUD_POSTGRESQL_DB_PASSWORD}
  database: ${GOOGLE_CLOUD_POSTGRESQL_DB_NAME}
  maxConns: 10
  sslmode : false

gcp:
  projectID: ${GOOGLE_PROJECT_ID}
  region: ${GOOGLE_REGION}
  instanceName: ${GOOGLE_CLOUD_POSTGRESQL_DB_INSTANCE_NAME}
  useIAMAuth: true
  credentialsFile: ${GCP_CREDS_FILE}
  usePrivateIP: false


grpc:
  serverPort: :50021
  clientAuthPort: :50011